# Generated by Django 4.2.1 on 2023-06-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('imagelink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='horrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('imagelink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='romance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('imagelink', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='cards',
            new_name='action',
        ),
    ]
