# Generated by Django 4.2.1 on 2023-06-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_action_imagelink_alter_anime_imagelink_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='horrer',
            new_name='horror',
        ),
    ]
