# Generated by Django 4.2.1 on 2023-06-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_rename_horrer_horror'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='facebooklink',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='gmaillink',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='instagramlink',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='twitterlink',
            field=models.TextField(null=True),
        ),
    ]
