# Generated by Django 4.2.1 on 2023-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_links_facebooklink_links_gmaillink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='gmaillink',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
