# Generated by Django 4.2.1 on 2023-06-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_links_gmaillink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='gmaillink',
        ),
    ]
