# Generated by Django 4.2.1 on 2023-06-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_remove_links_gmaillink'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadversion', models.TextField()),
                ('date', models.TextField()),
                ('changelog', models.TextField(default='Changelog', null=True)),
                ('changeslist', models.TextField(null=True)),
            ],
        ),
    ]
