# Generated by Django 4.2.1 on 2023-06-23 05:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_downloadpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadpage',
            name='changeslist',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
