# Generated by Django 4.2.1 on 2023-06-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_downloadpage_changeslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadpage',
            name='downloadversion',
        ),
        migrations.AddField(
            model_name='links',
            name='downloadversion',
            field=models.TextField(null=True),
        ),
    ]
